export const QUESTION_CREATE_REQUEST = 'QUESTION_CREATE_REQUEST'
export const QUESTION_CREATE_SUCCESS = 'QUESTION_CREATE_SUCCESS'
export const QUESTION_CREATE_FAIL = 'QUESTION_CREATE_FAIL'
export const QUESTION_CREATE_RESET = 'QUESTION_CREATE_RESET'

export const QUESTION_UPDATE_REQUEST = 'QUESTION_UPDATE_REQUEST'
export const QUESTION_UPDATE_SUCCESS = 'QUESTION_UPDATE_SUCCESS'
export const QUESTION_UPDATE_FAIL = 'QUESTION_UPDATE_FAIL'
export const QUESTION_UPDATE_RESET = 'QUESTION_UPDATE_RESET'


export const QUESTION_DELETE_REQUEST = 'QUESTION_DELETE_REQUEST'
export const QUESTION_DELETE_SUCCESS = 'QUESTION_DELETE_SUCCESS'
export const QUESTION_DELETE_FAIL = 'QUESTION_DELETE_FAIL'

export const QUESTION_DETAILS_REQUEST = 'QUESTION_DETAILS_REQUEST'
export const QUESTION_DETAILS_SUCCESS = 'QUESTION_DETAILS_SUCCESS'
export const QUESTION_DETAILS_FAIL = 'QUESTION_DETAILS_FAIL'

export const QUESTION_SHOW_REQUEST = 'QUESTION_SHOW_REQUEST'
export const QUESTION_SHOW_SUCCESS = 'QUESTION_SHOW_SUCCESS'
export const QUESTION_SHOW_FAIL = 'QUESTION_SHOW_FAIL'

export const QUESTION_SHOW_ONLY_REQUEST = 'QUESTION_SHOW_ONLY_REQUEST'
export const QUESTION_SHOW_ONLY_SUCCESS = 'QUESTION_SHOW_ONLY_SUCCESS'
export const QUESTION_SHOW_ONLY_FAIL = 'QUESTION_SHOW_ONLY_FAIL'

export const SHOW_ANSWER_BY_QUESTION_REQUEST = 'SHOW_ANSWER_BY_QUESTION_REQUEST'
export const SHOW_ANSWER_BY_QUESTION_SUCCESS = 'SHOW_ANSWER_BY_QUESTION_SUCCESS'
export const SHOW_ANSWER_BY_QUESTION_FAIL = 'SHOW_ANSWER_BY_QUESTION_FAIL'