export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const USER_ATTEMPT_REQUEST = 'USER_ATTEMPT_REQUEST'
export const USER_ATTEMPT_SUCCESS = 'USER_ATTEMPT_SUCCESS'
export const USER_ATTEMPT_FAIL = 'USER_ATTEMPT_FAIL'

export const ANSWER_SHEET_REQUEST = 'ANSWER_SHEET_REQUEST'
export const ANSWER_SHEET_SUCCESS = 'ANSWER_SHEET_SUCCESS'
export const ANSWER_SHEET_FAIL = 'ANSWER_SHEET_FAIL'

export const SHOW_TIME_REQUEST = 'SHOW_TIME_REQUEST'
export const SHOW_TIME_SUCCESS = 'SHOW_TIME_SUCCESS'
export const SHOW_TIME_FAIL = 'SHOW_TIME_FAIL'

export const UPDATE_TIME_REQUEST = 'UPDATE_TIME_REQUEST'
export const UPDATE_TIME_SUCCESS = 'UPDATE_TIME_SUCCESS'
export const UPDATE_TIME_FAIL = 'UPDATE_TIME_FAIL'